POST http://localhost:5000/create/
Content-Type: application/json

{
  "description": "Another todo"
}

###

GET http://localhost:5000/get/d7aae601-dbe0-4d5b-b8c9-d3c3552fe5d2

###

GET http://localhost:5000/delete/aac1a543-5354-4b7f-87ac-dd480738bba7

###

GET http://localhost:5000/list

###

GET http://localhost:5000/about