POST http://localhost:5000/create/
Content-Type: application/json

{
  "description": "Another todo"
}

###

GET http://localhost:5000/get/d7aae601-dbe0-4d5b-b8c9-d3c3552fe5d2

###

GET http://localhost:5000/delete/3e0a5386-16ae-46e6-917a-ed824652b081

###

GET http://localhost:5000/list

###

GET http://localhost:5000/about